### ISSUE TITLE
Does not work with python3

### ISSUE THREAD

**Issue by txtsd** [NuAoA/AnnouncementWindow#12]
```
┌[txtsd@dungeon-of-data]─[~/git/AnnouncementWindow] [126]                                                [15-12-13 21:46:51]
└─▶ python run.py                                                                                                            
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import Window
  File "/home/txtsd/git/AnnouncementWindow/Window.py", line 16, in <module>
    import Config
  File "/home/txtsd/git/AnnouncementWindow/Config.py", line 100, in <module>
    settings = config()
  File "/home/txtsd/git/AnnouncementWindow/Config.py", line 44, in __init__
    self.load()
  File "/home/txtsd/git/AnnouncementWindow/Config.py", line 67, in load
    self.parser.set(self.section, 'save_hidden_announcements', self.save_hidden_announcements)
  File "/usr/lib/python3.5/configparser.py", line 1189, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.5/configparser.py", line 1174, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

**Comment by txtsd** [comment]
That was on master.
On develop, the error is different.

```
┌[txtsd@dungeon-of-data]─[~/git/AnnouncementWindow]                                                      [15-12-13 21:51:24]
└─▶ python run.py                                                                                                            
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    root = Window.main_gui()
  File "/home/txtsd/git/AnnouncementWindow/Window.py", line 151, in __init__
    self.iconbitmap(Config.settings.icon_path)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1715, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "Data/favicon.ico" not defined
```

**Comment by NuAoA** [comment]
What OS are you using?

**Comment by txtsd** [comment]
Archlinux

**Comment by NuAoA** [comment]
Ah, well its present on windows too. At least the first error is. The second is most likely because its not correctly identifying your OS. 

Could you open your python interpreter, type `import sys` and tell me what typing `sys.platform` prints out?

**Comment by txtsd** [comment]
```
┌[txtsd@dungeon-of-data]─[~/git/AnnouncementWindow]                                                      [15-12-13 22:11:26]
└─▶ python                                                                                                                   
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'linux'
>>> exit()

┌[txtsd@dungeon-of-data]─[~/git/AnnouncementWindow]                                                      [15-12-13 22:15:03]
└─▶ python2                                                                                                                  
Python 2.7.11 (default, Dec  6 2015, 15:43:46) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'linux2'
```

**Comment by NuAoA** [comment]
Thank you.

Fixes for both problems are live on the develop branch.

**Comment by txtsd** [comment]
It works now! Thanks for the snappy fix :)
